# Use `ignore` to specify dependencies that should not be updated

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "autoprefixer"
        dependency-type: "development"
      - dependency-name: "browser-sync"
        dependency-type: "development"
      - dependency-name: "browsersync-webpack-plugin"
        dependency-type: "development"
      - dependency-name: "bs-html-injector"
        dependency-type: "development"
      - dependency-name: "buble-loader"
        dependency-type: "development"
      - dependency-name: "cache-loader"
        dependency-type: "development"
      - dependency-name: "clean-webpack-plugin"
        dependency-type: "development"
      - dependency-name: "copy-globs-webpack-plugin"
        dependency-type: "development"
      - dependency-name: "css-loader"
        dependency-type: "development"
      - dependency-name: "cssnano"
        dependency-type: "development"
      - dependency-name: "eslint"
        dependency-type: "development"
      - dependency-name: "eslint-loader"
        dependency-type: "development"
      - dependency-name: "eslint-plugin-import"
        dependency-type: "development"
      - dependency-name: "extract-text-webpack-plugin"
        dependency-type: "development"
      - dependency-name: "file-loader"
        dependency-type: "development"
      - dependency-name: "friendly-errors-webpack-plugin"
        dependency-type: "development"
      - dependency-name: "imagemin-mozjpeg"
        dependency-type: "development"
      - dependency-name: "imagemin-webpack-plugin"
        dependency-type: "development"
      - dependency-name: "import-glob"
        dependency-type: "development"
      - dependency-name: "node-sass"
        dependency-type: "development"
      - dependency-name: "postcss-loader"
        dependency-type: "development"
      - dependency-name: "postcss-safe-parser"
        dependency-type: "development"
      - dependency-name: "resolve-url-loader"
        dependency-type: "development"
      - dependency-name: "rimraf"
        dependency-type: "development"
      - dependency-name: "sass-loader"
        dependency-type: "development"
      - dependency-name: "style-loader"
        dependency-type: "development"
      - dependency-name: "stylelint"
        dependency-type: "development"
      - dependency-name: "stylelint-config-standard"
        dependency-type: "development"
      - dependency-name: "stylelint-webpack-plugin"
        dependency-type: "development"
      - dependency-name: "uglifyjs-webpack-plugin"
        dependency-type: "development"
      - dependency-name: "url-loader"
        dependency-type: "development"
      - dependency-name: "webpack"
        dependency-type: "development"
      - dependency-name: "webpack-assets-manifest"
        dependency-type: "development"
      - dependency-name: "webpack-dev-middleware"
        dependency-type: "development"
      - dependency-name: "webpack-hot-middleware"
        dependency-type: "development"
      - dependency-name: "webpack-merge"
        dependency-type: "development"
      - dependency-name: "yargs"
        dependency-type: "development"
