# Use `ignore` to specify dependencies that should not be updated

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "wordpress/wp-content/themes/linklives/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "autoprefixer"
      - dependency-name: "browser-sync"
      - dependency-name: "browsersync-webpack-plugin"
      - dependency-name: "bs-html-injector"
      - dependency-name: "buble-loader"
      - dependency-name: "cache-loader"
      - dependency-name: "clean-webpack-plugin"
      - dependency-name: "copy-globs-webpack-plugin"
      - dependency-name: "css-loader"
      - dependency-name: "cssnano"
      - dependency-name: "eslint"
      - dependency-name: "eslint-loader"
      - dependency-name: "eslint-plugin-import"
      - dependency-name: "extract-text-webpack-plugin"
      - dependency-name: "file-loader"
      - dependency-name: "friendly-errors-webpack-plugin"
      - dependency-name: "imagemin-mozjpeg"
      - dependency-name: "imagemin-webpack-plugin"
      - dependency-name: "import-glob"
      - dependency-name: "node-sass"
      - dependency-name: "postcss-loader"
      - dependency-name: "postcss-safe-parser"
      - dependency-name: "resolve-url-loader"
      - dependency-name: "rimraf"
      - dependency-name: "sass-loader"
      - dependency-name: "style-loader"
      - dependency-name: "stylelint"
      - dependency-name: "stylelint-config-standard"
      - dependency-name: "stylelint-webpack-plugin"
      - dependency-name: "uglifyjs-webpack-plugin"
      - dependency-name: "url-loader"
      - dependency-name: "webpack"
      - dependency-name: "webpack-assets-manifest"
      - dependency-name: "webpack-dev-middleware"
      - dependency-name: "webpack-hot-middleware"
      - dependency-name: "webpack-merge"
      - dependency-name: "yargs"
