version: "3.3"

services:

    db:
        container_name: db
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "./mysql:/docker-entrypoint-initdb.d"
        ports:
            - "3306:3306"

    wordpress:
        container_name: wordpress
        depends_on:
            - db
        build:
            context: .
            dockerfile: docker/wordpress-dev.Dockerfile
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_TABLE_PREFIX: wp_
            WORDPRESS_CONFIG_EXTRA: |
                define( 'URL', 'http://localhost' );
                define( 'WP_HOME', 'http://localhost' );
                define( 'WP_SITEURL', 'http://localhost' );
                define( 'WP_CACHE', false );
        ports:
            - "80:80"
        volumes:
            - "./wordpress/wp-content/themes/linklives/app:/var/www/html/wp-content/themes/linklives/app"
            - "./wordpress/wp-content/themes/linklives/config:/var/www/html/wp-content/themes/linklives/config"
            - "./wordpress/wp-content/themes/linklives/dist:/var/www/html/wp-content/themes/linklives/dist"
            - "./wordpress/wp-content/themes/linklives/resources:/var/www/html/wp-content/themes/linklives/resources"

    wordpress-dpl:
        container_name: wordpress-dpl
        depends_on:
            - db
        build:
            context: .
            dockerfile: docker/wordpress-deploy.Dockerfile
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_TABLE_PREFIX: wp_
            WORDPRESS_CONFIG_EXTRA: |
                define( 'URL', 'http://localhost' );
                define( 'WP_HOME', 'http://localhost' );
                define( 'WP_SITEURL', 'http://localhost' );
                define( 'WP_CACHE', false );
        ports:
            - "80:80"
        volumes:
            - "./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins"