version: "3.8"
services:
  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: ./docker/wordpress-dev.Dockerfile
    volumes:
      - "./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins"
      - "./wordpress/wp-content/uploads:/var/www/html/wp-content/uploads"
      - "/wp-content/wp-content/upgrade:/var/www/html/wp-content/upgrade"
      - "./wordpress/wp-content/languages:/var/www/html/wp-content/languages"
      - website-files:/var/www/html
    env_file: 
      - ./.env
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WORDPRESS_CONFIG_EXTRA=
          define( 'FS_METHOD', 'direct' );
          define( 'WORDPRESS_DEBUG','1' );
          define( 'WP_DEBUG_DISPLAY','1' );
          define( 'DISABLE_WP_CRON', true ); 
          define( 'WP_HOME', 'http://localhost' ); 
          define( 'WP_SITEURL', 'http://localhost' );
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes: 
      - website-files:/var/www/html
    depends_on:
      - wordpress
    ports:
      - 80:80
volumes:
    website-files: